### ISSUE TITLE
listtransactions is convoluted

### ISSUE THREAD

**Issue by darosior** [re-vault/revaultd#74]
We are trying to do too many things with  `listtransactions`. We need to split it into different purposes.

@edouardparis what do you need from the other side of the UDS ? :)

**Comment by edouardparis** [comment]
I agree that listransactions has too much things.
All the presigned transactions psbts are also in `getrevocationtxs`, this is quite a duplicate.
The revault-gui need to have a way to retrieve all broadcasted transactions of a vault.
That way when a stakeholder click on a unvaulting vault he can see
- the deposit transaction
- the unvaulting transaction
- the spend tx ?

**Comment by darosior** [comment]
So we are closer from a `listonchaintransactions` then ? Would something like:
```json
{
    "deposit": "hex", // Must be here if a vault exists in the first place
    "unvault": "hex", // Can be `null` !
    "cancel": "hex", // Can be `null` !
    "emergency": "hex", // Can be `null` !
    "unvault_emergency": "hex" // Can be `null`
}
```
Work for you ? Don't you have any other requirement than the optional onchain transactions ?

**Comment by edouardparis** [comment]
It works for me.
For the history panel, GUI needs a list of the deposit transactions and the spend transactions not filtered by vault_id

**Comment by darosior** [comment]
Ok, this can be done in a separate call to avoid the burden of querying the unvault, cancel, emergency and un_emergency for each vault.
What do you think of `spentvaults`:
```json
{
    {
         "deposit": "hex",
         "spend": "hex",
     },
     {
         "deposit": "hex",
         "spend": "hex",
     }
 }
 ```
 
 However i wonder why you don't ned eg the cancel for the history ?

**Comment by edouardparis** [comment]
Yes the cancel is equivalent of the spend.
>  the deposit transactions and the spend transactions not filtered by vault_id

I need more something like this:
```
[
      {
          hex: ...
          kind: deposit
       },
       {
          hex: ... // transaction who spend vault A
          kind: spend
       },
       {
          hex: ... // transaction who create vault A
          kind: deposit
       }
]
```

**Comment by darosior** [comment]
>  For the history panel, GUI needs a list of the deposit transactions and the spend transactions not filtered by vault_id

Ok, so that's a different call. Can you create another issue for discussing this one ?

Also, i'm not sure to grasp completely your example. How would you know for which vault is each of the transaction entry? Probably even better if you PR a doc draft so we can be more specific.
