### ISSUE TITLE
Fix bitcoind lag

### ISSUE THREAD

**Issue by darosior** [re-vault/revaultd#82]
https://github.com/re-vault/revaultd/commit/a4690dfc334a3daaf71885b4e2b60afc358479a6 was purely dumb, but i don't want to get back to 100% CPU..

**Comment by edouardparis** [comment]
bitcoind_main_loop could use https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.iter instead of try_recv in order to block the thread, and A ticker could send to bitcoin_main_loop a tick in order to check the blockchain tip.

**Comment by darosior** [comment]
Yes, i was thinking either this or just spawn the poller in a separate thread.

**Comment by edouardparis** [comment]
A mix of both would be cool :+1: 
thread with receiver should use `iter`

**Comment by darosior** [comment]
Yeah, the poller was the reason we could not use an iterator in the first place

**Comment by darosior** [comment]
Ok, lest fix it post https://github.com/re-vault/revaultd/issues/73 .
